import time
import os
import requests
from dataclasses import dataclass, asdict
from typing import List, Dict, Optional
from datetime import datetime, timezone

from ratelimit import limits, sleep_and_retry
from config import VT_API_KEY, settings
from error_handler import safe_api_call, RateLimitError, TimeoutError, ValidationError
from logger_config import setup_logger

logger = setup_logger(__name__)

# Read rate limit from config.yaml
VT_CONFIG = settings["api"]["virustotal"]
RATE_LIMIT = VT_CONFIG["rate_limit"]  # 4

CALLS = 1
PERIOD = 60 / RATE_LIMIT


# ========== Data Model ==========
@dataclass
class IOC:
    """Standardlized IOC data model fordatabase insertion."""

    alert_id: Optional[int] = None  # auto_generated by DB
    ioc_value: str = ""
    ioc_type: str = ""  # ipv4, ipv6, domain, url, md5, sha256
    risk_score: int = 0
    risk_level: str = "LOW"  # HIGH, MEDIUM, LOW
    source_name: str = ""
    threat_actor: Optional[str] = None
    created_at: Optional[str] = None

    def to_dict(self) -> Dict:
        return asdict(self)


# ========== VirusTotsl Client ==========
class VTClient:
    """
    VirusTotal API client for fetching threat intelligence.
    """

    def __init__(self):
        self.api_key = VT_API_KEY
        self.base_url = VT_CONFIG["base_url"]
        self.timeout = VT_CONFIG["timeout"]
        self.headers = {"x-apikey": self.api_key, "Accept": "application/json"}

    @sleep_and_retry
    @limits(calls=CALLS, period=PERIOD)
    def _fetch(self, url: str) -> Optional[Dict]:
        """Internal fetch with rate limiting."""
        response = requests.get(url, headers=self.headers, timeout=self.timeout)

        if response.status_code == 429:
            raise RateLimitError("VT rate limit exceeded")
        elif response.status_code >= 500:
            raise TimeoutError(f"VT server error: {response.status_code}")
        elif response.status_code == 404:
            return None  # Not found, not malicious

        response.raise_for_status()
        return response.json()

    def _calculate_risk(self, stats: Dict) -> tuple[int, str]:
        """Calculate risk score and level from analysis stats."""
        malicious = stats.get("malicious", 0)
        suspicious = stats.get("suspicious", 0)
        harmless = stats.get("harmless", 0)
        total = malicious + suspicious + harmless

        if total == 0:
            return 0, "LOW"

        # Weighted score: malicious=2x, suspicious=1x
        score = min(100, int((malicious * 2 + suspicious) / total * 100))

        if score >= 70:
            return score, "HIGH"
        elif score >= 40:
            return score, "MEDIUM"
        return score, "LOW"

    def _extract_stats(self, result: Optional[Dict]) -> Optional[Dict]:
        """Extract analysis stats from VT response."""
        if not result:
            return None
        data = result.get("data", {})
        attributes = data.get("attributes", {})
        return attributes.get("last_analysis_stats", {})

    def get_ip_report(self, ip_address: str) -> Optional[IOC]:
        """Fetch IP report and return standardized IOC."""
        url = f"{self.base_url}/ip_addresses/{ip_address}"

        try:
            logger.info(f"Quering IP: {ip_address}")
            result = safe_api_call(lambda: self._fetch(url), max_retries=3)
            stats = self._extract_stats(result)

            if not stats:
                logger.warning(f"No data for IP: {ip_address}")
                return None

            score, level = self._calculate_risk(stats)

            return IOC(
                ioc_value=ip_address,
                ioc_type="ipv4",
                risk_score=score,
                risk_level=level,
                source_name="virustotal",
                created_at=datetime.now(timezone.utc).isoformat(),
            )
        except Exception as e:
            logger.error(f"Failed to fetch IP {ip_address}: {str(e)}")
            return None

    def get_domain_report(self, domain: str) -> Optional[IOC]:
        """Fetch domain report and return standardized IOC."""
        url = f"{self.base_url}/domains/{domain}"

        try:
            logger.info(f"Querying VT domain: {domain}")
            result = safe_api_call(lambda: self._fetch(url), max_retries=3)
            stats = self._extract_stats(result)

            if not stats:
                return None

            score, level = self._calculate_risk(stats)

            return IOC(
                ioc_value=domain,
                ioc_type="domain",
                risk_score=score,
                risk_level=level,
                source_name="virustotal",
                created_at=datetime.now(timezone.utc).isoformat(),
            )

        except Exception as e:
            logger.error(f"Failed to fetch domain {domain}: {str(e)}")
            return None

    def get_file_report(self, file_hash: str) -> Optional[IOC]:
        """Fetch file hash report and return standardized IOC."""
        url = f"{self.base_url}/files/{file_hash}"

        try:
            logger.info(f"Querying VT file: {file_hash}")
            result = safe_api_call(lambda: self._fetch(url), max_retries=3)
            stats = self._extract_stats(result)

            if not stats:
                return None

            score, level = self._calculate_risk(stats)

            hash_type = (
                "sha256"
                if len(file_hash) == 64
                else "md5" if len(file_hash) == 32 else "sha1"
            )

            return IOC(
                ioc_value=file_hash,
                ioc_type=hash_type,
                risk_score=score,
                risk_level=level,
                source_name="virustotal",
                created_at=datetime.now(timezone.utc).isoformat(),
            )
        except Exception as e:
            logger.error(f"Failed to fetch file {file_hash}: {str(e)}")
            return None


# ======== OTX Client ========
class OTXClient:
    """AlienVault OTX API client."""

    BASE_URL = "https://otx.alienvault.com/api/v1"

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("OTX_API_KEY")
        self.headers = {"X-OTX-API-KEY": self.api_key} if self.api_key else {}

    def _fetch(self, endpoint: str) -> Optional[Dict]:
        """Make OTX API request."""
        url = f"{self.BASE_URL}/{endpoint}"
        try:
            response = requests.get(url, headers=self.headers, timeout=30)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.HTTPError as e:
            if response.status_code == 400:
                logger.warning(f"OTX 400 Bad Request: {url}")
                return None
            if response.status_code == 429:
                logger.warning("OTX rate limit, waiting...")
                time.sleep(60)
                return self._fetch(endpoint)
            logger.error(f"OTX error: {e}")
            return None
        except requests.exceptions.Timeout:
            logger.warning(f"OTX timeout: {url}")
            return None
        except Exception as e:
            logger.error(f"OTX request failed: {e}")
            return None

    def get_ip_reputation(self, ip: str) -> Optional[IOC]:
        """Get IP reputation from OTX."""
        data = self._fetch(f"indicators/IPv4/{ip}/general")
        if not data:
            return None

        # Determine the threat level based on the "pulse_info" (the "reputation" field may not exist or be None)
        pulse_info = data.get("pulse_info", {})
        pulse_count = pulse_info.get("count", 0)

        # Calculate the score: 0 - 20 pulses are mapped to 0 - 100
        score = min(100, pulse_count * 5)

        level = "HIGH" if score >= 70 else "MEDIUM" if score >= 40 else "LOW"

        return IOC(
            ioc_value=ip,
            ioc_type="ipv4",
            risk_score=score,
            risk_level=level,
            source_name="otx",
            created_at=datetime.now(timezone.utc).isoformat(),
        )

    def get_domain_reputation(self, domain: str) -> Optional[IOC]:
        """Get domain reputation from OTX."""
        data = self._fetch(f"indicators/domain/{domain}/general")
        if not data:
            return None

        # Use pulse count as indicator
        pulse_count = len(data.get("pulse_info", {}).get("pulses", []))
        score = min(100, pulse_count * 5)  # 20 pulses = 100

        level = "HIGH" if score >= 70 else "MEDIUM" if score >= 40 else "LOW"

        return IOC(
            ioc_value=domain,
            ioc_type="domain",
            risk_score=score,
            risk_level=level,
            source_name="otx",
            created_at=datetime.now(timezone.utc).isoformat(),
        )


# ======== Unified Fetcher ========
class IntelFetcher:
    """Unified fetcher that queries multiple sources."""

    def __init__(self):
        self.vt = VTClient()
        self.otx = OTXClient()

    def fetch_ip(self, ip: str, sources: List[str] = None) -> List[IOC]:
        """Fetch IP from all configured sources."""
        sources = sources or ["vt", "otx"]
        results = []

        if "vt" in sources:
            vt_result = self.vt.get_ip_report(ip)
            if vt_result:
                results.append(vt_result)

        if "otx" in sources and self.otx.api_key:
            otx_result = self.otx.get_ip_reputation(ip)
            if otx_result:
                results.append(otx_result)
        return results

    def fetch_domain(self, domain: str, sources: List[str] = None) -> List[IOC]:
        """Fetch domain from all configured sources."""
        sources = sources or ["vt", "otx"]
        results = []

        if "vt" in sources:
            vt_result = self.vt.get_domain_report(domain)
            if vt_result:
                results.append(vt_result)

        if "otx" in sources and self.otx.api_key:
            otx_result = self.otx.get_domain_reputation(domain)
            if otx_result:
                results.append(otx_result)

        return results

    def fetch_batch(self, items: List[Dict]) -> List[IOC]:
        """
        Fetch batch of IOCs.
        items: [{"type": "ipv4", "value": "1.2.3.4"}, {"type": "domain", "value": "evil.com"}]
        """
        all_results = []

        for item in items:
            ioc_type = item.get("type")
            value = item.get("value")

            if ioc_type == "ipv4":
                results = self.fetch_ip(value)
            elif ioc_type == "domain":
                results = self.fetch_domain(value)
            else:
                logger.warning(f"Unsupported type: {ioc_type}")
                continue
            all_results.extend(results)
            time.sleep(1)  # Be nice to APIs

        return all_results


# ======== Test ========
if __name__ == "__main__":
    fetcher = IntelFetcher()

    # Test VT
    print("=== Testing VT ===")
    vt_result = fetcher.vt.get_ip_report("8.8.8.8")
    if vt_result:
        print(f"[OK] VT: {vt_result}")
    else:
        print("[INFO] VT returned no data (likely clean IP)")

    # Test OTX (if key available)
    if fetcher.otx.api_key:
        print("\n=== Testing OTX ===")
        otx_result = fetcher.otx.get_ip_reputation("8.8.8.8")
        if otx_result:
            print(f"[OK] OTX: {otx_result}")
    else:
        print("\n[INFO] OTX_API_KEY not set, skipping OTX test")

    # Test batch
    print("\n=== Testing Batch ===")
    test_items = [
        {"type": "ipv4", "value": "8.8.8.8"},
        {"type": "ipv4", "value": "1.1.1.1"},
        {"type": "domain", "value": "google.com"},
    ]
    batch_results = fetcher.fetch_batch(test_items)
    print(f"Fetched {len(batch_results)} IOCs from {len(test_items)} queries")
    for ioc in batch_results:
        print(
            f"  - {ioc.ioc_type}: {ioc.ioc_value} -> {ioc.risk_level} ({ioc.risk_score})"
        )
