"""Add indexes

Revision ID: 0af9e28cf1c1
Revises: f04f44ff4a9e
Create Date: 2026-07-16 22:42:24.468300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af9e28cf1c1'
down_revision: Union[str, Sequence[str], None] = 'f04f44ff4a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iocs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ioc_last_seen', 'iocs', ['last_seen'], unique=False)
    op.create_index('idx_ioc_type', 'iocs', ['type'], unique=False)
    op.create_index('idx_ioc_value', 'iocs', ['value'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_source_name', 'sources', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alert_ioc_source', 'alerts', ['ioc_id', 'source_id'], unique=False)
    op.create_index('idx_alert_risk_level', 'alerts', ['risk_level'], unique=False)
    op.create_table('attributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attr_actor', 'attributions', ['actor_name'], unique=False)
    op.create_index('idx_attr_ioc', 'attributions', ['ioc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attr_ioc', table_name='attributions')
    op.drop_index('idx_attr_actor', table_name='attributions')
    op.drop_table('attributions')
    op.drop_index('idx_alert_risk_level', table_name='alerts')
    op.drop_index('idx_alert_ioc_source', table_name='alerts')
    op.drop_index('idx_alert_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_source_name', table_name='sources')
    op.drop_table('sources')
    op.drop_index('idx_ioc_value', table_name='iocs')
    op.drop_index('idx_ioc_type', table_name='iocs')
    op.drop_index('idx_ioc_last_seen', table_name='iocs')
    op.drop_table('iocs')
    # ### end Alembic commands ###
